author: "Shimushu"
avatar: "/assets/img/avatar2.png"
icon:   "/assets/img/avatar2.png"

katex: true

title: "Shimushu"

blog: "/blog/"

paginate: 3
paginate_path: "/blog/page/:num/"

plugins: [jekyll-paginate]

# For RSS feed
name:        "Shimushu" 
description: "..."
url:         "https://shimushushushu.github.io"